### ISSUE TITLE
Events Midpage

### ISSUE THREAD

**Issue by halfempty** [clockshop/clockshopwp#1]
**Mackenzie says:**

> Can we change the placement of the Events on this page? It would be better if they appeared after the biography information and before the partnerships and funding sources. Logos and partnerships of this kind would always appear in that same place.

**Comment by Clockshopla** [comment]
@halfempty just checking one more time to see if this a possible thing? Basically we just want the logos and funders below the calendar events so people will continue scrolling.

**Comment by Clockshopla** [comment]
@halfempty actually could we just do a jump down link to where the events start? Then we can just add a line under the description that says view full calendar and jumps you down.

**Comment by halfempty** [comment]
@Clockshopla Okay, you can now link to `#events` on that page

**Comment by Clockshopla** [comment]
@halfempty okay so I just hyperlink the text and enter #events as the link address?

**Comment by halfempty** [comment]
@Clockshopla Exactly!

**Comment by Clockshopla** [comment]
Got it thanks!
