### ISSUE TITLE
Clockshop Footer 

### ISSUE THREAD

**Issue by tkracauer** [clockshop/clockshopwp#10]
@halfempty 

Thanks for sending over the mockup of the footer. Here are our notes:

- Let's hold off on the video portal for now, it seems like it would require an additional page for all of Clockshop's media
- The text we want in the subscribe footer: “Subscribe to our mailing list”, no need to have any more text than this
- Perhaps the lines/rules could be contained within the content column (instead of running across the whole width of the browser window) so they don’t collide with the C logo or the Clockshop logo type when user scroll down

**Please email Mackenzie and Julia a quote and a schedule for the footer work (do not include work related to the video portion of the footer). It's a great idea it's just out of the scope of what we can take on right now.** 

Current: LA Water opens this weekend and if at all possible it would be AMAZING and very useful to us to have the footer+contact info section completed by this weekend.

**Comment by halfempty** [comment]
@tkracauer @Clockshopla Hey guys, just got the updated mssg: re deadline. I wrote to Julia re: budget and am going to hop onto the site now and what I can get done for tomorrow.

**Comment by halfempty** [comment]
@tkracauer @Clockshopla Okay, I've done this:

![image](https://cloud.githubusercontent.com/assets/775543/16890399/d3d7eb1e-4ab3-11e6-9e69-e967e2ed447e.png)

Did it super quick and it could definitely be refined. Hopefully it'll get us through this weekend, tho! 

Mackenzie, you'll get an email when someone subscribes. The email addresses will need to be manually entered into NB.

**Comment by tkracauer** [comment]
@halfempty @Clockshopla 

Hi Marty, 

I'm just checking in on the integration of the subscribe form to nationbuilder. 

Tk

**Comment by halfempty** [comment]
@tkracauer @Clockshopla It's still sitting with NB. I've just left them a voicemail. I'll update you when I hear back.

**Comment by tkracauer** [comment]
@halfempty @Clockshopla 

Thanks, Marty

**Comment by halfempty** [comment]
@tkracauer @Clockshopla okay, they've given me access (I stressed that this was becoming a problem for us). Awesome!

Now I've ping'd Daniel to ask him if he's got a moment to walk me through the configuration (he being the fellow who developed the WP->NB integration). If he's unavailable to connect today I'll read through the docs myself and proceed with the setup.

**Comment by halfempty** [comment]
@tkracauer @Clockshopla Okay, I think the newsletter form in the footer is sending to NB. I subscribed "info@spellerbergprojects.com" that way, and I see it showing up on the NB side. Will y'all take a look and confirm? Maybe try subscribing an address of your own? Thanks!

**Comment by tkracauer** [comment]
@halfempty @Clockshopla 

We've tested it and it works on chrome but doesnt seem to work on safari. have you tested it on that browser? Mackenzie is still receiving an email with the subscribers email address. Any idea how to make those stop?

**Comment by halfempty** [comment]
@tkracauer @Clockshopla Works in Safari for me. Just signed-up "hellotom@martyspellerberg.com" using it.

Yes, to turn off those emails, navigate to the forms are of WP, locate the newsletter signup form, then go to settings->notifications. Turn off the one that's enabled. (I can do that as well, but good if y'all know how that works)

**Comment by tkracauer** [comment]
@halfempty 
Thanks Marty! I'll let Mackenzie know. 

Tk
