### ISSUE TITLE
Vimeo embeds in Radio Imagination Template pages

### ISSUE THREAD

**Issue by tkracauer** [clockshop/clockshopwp#13]
Hi @halfempty 

We're experiencing a problem with embedding videos from vimeo on the Radio Imagination template pages. The videos are rendering at what seems like half the column width. See : https://clockshop.org/project/trailers-and-videos/

We don't seem to have this problem on the Bowtie Project template pages. 

We're spending the next couple of days repopulating the Radio Imagination portion of the site to fit the new nav system so some help on this soon would be highly appreciated.

![ri-trailer-screencap](https://cloud.githubusercontent.com/assets/20051176/17673969/5044d554-62d8-11e6-9f66-f989e78dee03.png)

**Comment by halfempty** [comment]
@tkracauer Interesting bug. I've put in a quick fix

**Comment by tkracauer** [comment]
Thanks, @halfempty !
