### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by halfempty** [clockshop/clockshopwp#3]

**Comment by Clockshopla** [comment]
@halfempty How is the responsive updating going?

**Comment by halfempty** [comment]
@Clockshopla I've been working on this. I'm not 100% done, but I have the main navigation mechanism working. Please take a look here:

http://dev.clockshop.org/about/
(Pull it up on your phone for the full effect)

I went with the black top to make it stand out against the page body. Is that cool with y'all?

**Comment by Clockshopla** [comment]
@halfempty Looks good. The black bar works fine. Will there be a home page?

**Comment by halfempty** [comment]
@Clockshopla I can add a link to home

**Comment by Clockshopla** [comment]
@halfempty thanks. from the logo would be great.

**Comment by Clockshopla** [comment]
@halfempty Got the home page. Can you move the social media stuff down to the bottom of the page. It's covering the menu dropdown. 

The Next symbol isn't working at all. I think it would be fine to drop that on the homepage all together, if  it's not possible to scale it down.

**Comment by halfempty** [comment]
@Clockshopla I know; I'm not finished! I'll ping you again when I've done. I just wanted you to see the black before I did the rest.

**Comment by halfempty** [comment]
@Clockshopla Okay, I think I've got the homepage and other various bits and pieces working responsively. I'm going to go ahead and apply this update, but please keep an eye out and let me know if you notice any glitches. Thanks!

**Comment by Clockshopla** [comment]
@halfempty I was just making edits to the website and found a glitch! The Octavia Butler Legacy Network Logo is huge!

**Comment by Clockshopla** [comment]
Will keep an eye out for other glitches.

**Comment by halfempty** [comment]
@Clockshopla Which page is that logo on? Thanks!

**Comment by Clockshopla** [comment]
Radio Imagination

**Comment by halfempty** [comment]
@Clockshopla will you please remove the password from that page temporarily so I can see?

**Comment by halfempty** [comment]
@Clockshopla okay, I've converted the size on those logos to CSS (same technique as we use on the About page)

**Comment by Clockshopla** [comment]
@halfempty  great thank you! 

still need to remove the password?

**Comment by halfempty** [comment]
@Clockshopla no, it's cool now

**Comment by Clockshopla** [comment]
@halfempty does the responsiveness include scaling for laptops as well? I can't tell entirely.

**Comment by halfempty** [comment]
@Clockshopla At larger sizes the design is as it was before, which was already optimized for that size. Does that make sense?

**Comment by Clockshopla** [comment]
@halfempty Oh okay. Got it. Thank you.
