### ISSUE TITLE
Radio Imagination identity

### ISSUE THREAD

**Issue by halfempty** [clockshop/clockshopwp#4]
**@Clockshopla said:**

> We have created a graphic identity for the Radio Imagination series that we would like to somehow incorporate into the project page for the series. What would be the most cost effective way to do this? We thought maybe changing the backdrop color and adding the logo title card at top might be enough.

**Comment by halfempty** [comment]
@Clockshopla Looks good. Would the background color be the yellow?

**Comment by Clockshopla** [comment]
@halfempty I think we start with the blue. We might also want to add that pixel graphic too if easy.

**Comment by halfempty** [comment]
@Clockshopla Okay, I've tinted that page blue:

http://clockshop.org/project/radio-imagination/

What you had in mind? 
The pixel graphic wouldn't be so easy, unfortunately.

**Comment by Clockshopla** [comment]
@halfempty Thanks. This is really helpful to see. We'll need a couple days to decide.

**Comment by Clockshopla** [comment]
Is it easy to change the color of the background? We want to try some other colors out and it would be easier if we could do that in house.

**Comment by halfempty** [comment]
@Clockshopla Would you like me to do a screenshot against white, which you could tint in Photoshop?

**Comment by Clockshopla** [comment]
@halfempty Oh yeah that would work. Thanks!

**Comment by halfempty** [comment]
@Clockshopla Let me know if this works: https://www.dropbox.com/s/y1rzj1j81heu7am/radioimagination.psd?dl=0

**Comment by halfempty** [comment]
@Clockshopla And here it is as a flattened file:

![radioimagination](https://cloud.githubusercontent.com/assets/775543/12248147/2099ca40-b87d-11e5-8205-349733719a87.png)

**Comment by Clockshopla** [comment]
hi @halfempty we've decided to stick with the white background and incorporate the color in the graphics for each event instead. thanks!

**Comment by Clockshopla** [comment]
@halfempty is it possible to get the white updated today? We need to send a preview out to someone this afternoon. Thanks!

**Comment by halfempty** [comment]
@Clockshopla You'd like me to turn Radio Imagination back to white?

**Comment by Clockshopla** [comment]
@halfempty yes please.

**Comment by halfempty** [comment]
@Clockshopla ok, done
