### ISSUE TITLE
calendar q

### ISSUE THREAD

**Issue by Clockshopla** [clockshop/clockshopwp#6]
@halfempty Is it possible to do a calendar listing with just a month and no date yet? We have an event we want to include during the press release but are waiting on someone to nail down the exact date. 

Thanks!

**Comment by halfempty** [comment]
@Clockshopla Hmm, actually I'm not sure how to achieve that using strictly the calendar. It revolves around dates. What we might try is creating a page elsewhere on the site with the existing info, and then recreate + redirect it to the event when we have the date?

**Comment by Clockshopla** [comment]
@halfempty oh yeah that would work. I created "projects" for the other pages we needed for Radio Imagination. Was creating a "page" the better way to go? The Videos and Octavia E. Butler pages are projects that link from this project. I can correct it.

**Comment by halfempty** [comment]
@Clockshopla If Project is working for now, let's leave it
